<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SysDiag">
      <HintPath>..\..\bin\Debug\net8.0-windows\win-x64\SysDiag.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
